services:
  bot:
    build: .
    restart: unless-stopped

    env_file:
      - .env

    environment:
      - FLARESOLVERR_URL=http://flaresolverr:8191/v1
      - LAVALINK_URL=lavalink:2333
      - LAVALINK_PASSWORD=${LAVALINK_PASSWORD}

    volumes:
      - ./bot.log:/app/bot.log
      - ./bot.db:/app/bot.db
      - ./src:/app/src/

    depends_on:
      - flaresolverr
      - lavalink

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
    ports:
      - "8191:8191"

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx1G
      - LAVALINK_PASSWORD=${LAVALINK_PASSWORD}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    ports:
      - "2333:2333"

